repos:
# Tests if there are spelling errors in the code.
 - repo: https://github.com/codespell-project/codespell
   rev: v2.2.6
   hooks:
    - id: codespell

# Runs additional tests that are created by the pre-commit software itself.
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.5.0
   hooks:
    # Check user did not add large files.
    #- id: check-added-large-files
    # Check if `.py` files are written in valid Python syntax.
    - id: check-ast
    # Require literal syntax when initializing empty or zero Python builtin types.
    - id: check-builtin-literals
    # Checks if there are filenames that would conflict if case is changed.
    - id: check-case-conflict
    # Checks if the Python functions have docstrings.
    - id: check-docstring-first
    # Checks if any `.sh` files have a shebang like #!/bin/bash
    - id: check-executables-have-shebangs
    # Verifies json format of any `.json` files in repo.
    - id: check-json
    # Checks if there are any existing merge conflicts caused by the commit.
    - id: check-merge-conflict
    # Checks for symlinks which do not point to anything.
    - id: check-symlinks
    # Checks if xml files are formatted correctly.
    - id: check-xml
    # Checks if .yml files are valid.
    - id: check-yaml
    # Checks if debugger imports are performed.
    - id: debug-statements
    # Detects symlinks changed to regular files with content path symlink was pointing to.
    - id: destroyed-symlinks
    # Checks if you don't accidentally push a private key.
    - id: detect-private-key
    # Replaces double quoted strings with single quoted strings.
    # This is not compatible with Python Black.
    #- id: double-quote-string-fixer
    # Makes sure files end in a newline and only a newline.
    - id: end-of-file-fixer
    # Removes UTF-8 byte order marker.
    - id: fix-byte-order-marker
    # Add <# -*- coding: utf-8 -*-> to the top of python files.
    #- id: fix-encoding-pragma
    # Checks if there are different line endings, like \n and crlf.
    - id: mixed-line-ending
    # Asserts `.py` files in folder `/test/` (by default:) end in `_test.py`.
    - id: name-tests-test
      # Override default to check if `.py` files in `/test/` START with `test_`.
      args: ['--django']
    # Ensures JSON files are properly formatted.
    - id: pretty-format-json
      args: ['--autofix']
    # Sorts entries in requirements.txt and removes incorrect pkg-resources entries.
    - id: requirements-txt-fixer
    # Sorts simple YAML files which consist only of top-level keys.
    - id: sort-simple-yaml
    # Removes trailing whitespaces at end of lines of .. files.
    - id: trailing-whitespace





 - repo: https://github.com/PyCQA/autoflake
   rev: v2.2.1
   hooks:
    - id: autoflake
      args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports", "--recursive"]
      name: AutoFlake
      description: "Format with AutoFlake"
      stages: [commit]

# Enforces formatting style in Markdown (.md) files.
 - repo: https://github.com/executablebooks/mdformat
   rev: 0.7.17
   hooks:
   - id: mdformat
     #args: ["-r ~MD013"]
     additional_dependencies:
     - mdformat-toc
     - mdformat-gfm
     - mdformat-black

 - repo: https://github.com/myint/docformatter
   rev: v1.7.5
   hooks:
   - id: docformatter



 - repo: https://github.com/markdownlint/markdownlint
   rev: v0.12.0
   hooks:
     - id: markdownlint

 - repo: https://github.com/Bahjat/pre-commit-golang
   rev: v1.0.3
   hooks:
    -   id: go-fmt-import
    -   id: go-vet
    -   id: go-lint
    -   id: go-unit-tests
    -   id: gofumpt
    -   id: go-err-check
    -   id: go-static-check
    -   id: golangci-lint
        args:
        - --config=.github/linters/.golangci.yml
    -   id: go-ruleguard
        args:
        - rules/rules.go
 - repo: https://github.com/dnephin/pre-commit-golang
   rev: v0.5.1
   hooks:
    - id: go-fmt
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: validate-toml
    # - id: no-go-testing
    - id: go-critic
    - id: go-build
    - id: go-mod-tidy
